### ISSUE TITLE
Numbers vs strings

### ISSUE THREAD

**Issue by jaydenseric** [jsonmaur/zoo#2]
I am running into issues that everything is set as a string.

In my situation with Next.js, I want to be able to do this:

```
"scripts": {
  "dev": "zoo next -p $PORT"
}
```

Because `process.env.PORT` is a string this fails with a listen error.

Could we allow for automatic parsing of numbers?

Perhaps everything not wrapped in quotes is interpreted as a number.

**Comment by jsonmaur** [comment]
I think since the `.env` file doesn't require quotes around string values (e.g. `NAME=VALUE` works as well as `NAME="VALUE"`), there is not a good way to accurately typecast numbers. The problem would be better solved in Next, where they should typecast the port number if it's passed as a string.
